!!python/object:argparse.Namespace
dataset: synbols
n_shots: 5
n_ways: 4
timesteps: 10000
deeper: 0
hidden_size: 64
prob_statio: 0.0
model_name: ANIL
model_name_impv: ANIL
n_pretrain_epochs: 1000
patience: 20
pretrain_batch_size: 4
meta_lr: 0.001
num_steps: 16
step_size: 0.005
first_order: 1
learn_step_size: false
per_param_step_size: false
cl_accumulate: false
cl_strategy: never_retrain
cl_strategy_thres: 0.0
cl_tbd_thres: -1.0
mean_eta: 0.001
std_init: 0.01
l1_reg: 0.0
masks_init: 0.5
prob_env_switch: 1.0
pretrain_model: models/synbols_maml.model
