!!python/object:argparse.Namespace
dataset: synbols
n_shots: 5
n_ways: 4
timesteps: 10000
deeper: 0
hidden_size: 64
prob_statio: 0.0
model_name: CMAML
model_name_impv: CMAML_kwto_acc
n_pretrain_epochs: 0
patience: 20
pretrain_batch_size: 8
meta_lr: 0.0005
num_steps: 4
step_size: 0.1
first_order: 0
learn_step_size: true
per_param_step_size: true
cl_accumulate: true
cl_strategy: loss_smooth
cl_strategy_thres: 1.0
cl_tbd_thres: 1.25
mean_eta: 0.001
std_init: 0.01
l1_reg: 0.0
masks_init: 0.5
prob_env_switch: 1.0
pretrain_model: models/synbols_maml.model
