!!python/object:argparse.Namespace
dataset: synbols
n_shots: 5
n_shots_test: 15
m_tr: 5 #n_shots + n_shots_test, pretrain, same sample complexity as MAML. validation is used for evaluation not update parameters
m_va: 15
n_ways: 4
timesteps: 10000
deeper: 0
hidden_size: 64
prob_statio: 0.0
prob_env_switch: 1.0
model_name: DCML
model_name_impv: DCML_oracle
method: DMOGD
base_algo: SGD
meta_algo: OGD
K: 16 # inner steps
inner_batch_size: 20
L: 200
alpha: 4.0
D_hat_guess: 100
rho: 0.2
eta_0: 20
epsilon_0_rate: 4.0
switch_method: 3 #oracle-1, BOCD-2, sliding win-3, static-4
win: 1
pretrain_model: models/synbols_maml.model
