!!python/object:argparse.Namespace
dataset: synbols
n_shots: 5
n_ways: 4
timesteps: 10000
deeper: 0
hidden_size: 64
prob_statio: 0.0
model_name: CMAML
model_name_impv: CMAML_pre_acc
n_pretrain_epochs: 1000
patience: 10
pretrain_batch_size: 16
meta_lr: 0.001
num_steps: 16
step_size: 0.05
first_order: 0
learn_step_size: true
per_param_step_size: true
cl_accumulate: true
cl_strategy: always_retrain
cl_strategy_thres: 1.0
cl_tbd_thres: -2
mean_eta: 0.001
std_init: 0.01
l1_reg: 0.0
masks_init: 0.5
prob_env_switch: 0.2
pretrain_model: models/synbols_maml.model
