!!python/object:argparse.Namespace
dataset: omniglot
n_shots: 5
n_ways: 10
timesteps: 10000
deeper: 0
hidden_size: 64
prob_statio: 0.0
model_name: CMAML
model_name_impv: CMAML
n_pretrain_epochs: 0
patience: 5
pretrain_batch_size: 1
meta_lr: 0.0005
num_steps: 2
step_size: 0.001
first_order: 0
learn_step_size: true
per_param_step_size: true
cl_accumulate: false
cl_strategy: loss_smooth
cl_strategy_thres: 1000.0
cl_tbd_thres: 1000.0
mean_eta: 0.001
std_init: 0.01
l1_reg: 0.0
masks_init: 0.5
prob_env_switch: 0.8
pretrain_model: models/omniglot_maml.model
